version: "3.3"
services:
  postgres:
    image: postgres:${CONTAINER_PG_VERSION:-11}
  code:
    build: .
    image: pg_party
    environment:
      - CC_TEST_REPORTER_ID
    links:
      - postgres
    volumes:
      - .:/code
