version: 2.0
jobs:
  build:
    docker:
      - image: tmaier/docker-compose

    steps:
      - setup_remote_docker

      - checkout

      - run: docker-compose up -d

      - run: docker cp . repo_project_1:/project

      - run: bin/de bundle

      - run: bin/de rake
