version: 2.0
jobs:
  build:
    docker:
      - image: tmaier/docker-compose

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Prepare and start containers
          command: |
            docker-compose up -d
            docker cp . project_code_1:/code

      - run:
          name: Install gems
          command: bin/de bundle

      - run:
          name: Run tests
          command: bin/de rake ci

      - run:
          name: Attempt to copy test results from container
          when: always
          command: |
            set +e
            mkdir -p /tmp/results
            docker cp project_code_1:/code/spec/reports/rspec.xml /tmp/results/rspec.xml
            /bin/true

      - store_test_results:
          path: /tmp/results
