shared_config: &shared_config
  machine:
    image: circleci/classic:edge

  steps:
    - checkout

    - run:
        name: Prepare and start containers
        command: |
          docker-compose build --build-arg CONTAINER_RUBY_VERSION=$CONTAINER_RUBY_VERSION code
          docker-compose up -d

    - run:
        name: Install global gems
        command: bin/de bundle

    - run:
        name: Install appraisal gems
        command: bin/de appraisal

    - run:
        name: Run tests
        command: bin/de appraisal rake ci

    - store_test_results:
        path: spec/results

version: 2
jobs:
  build-ruby-2.2.2:
    <<: *shared_config

    environment:
      CONTAINER_RUBY_VERSION: 2.2.2

  build-ruby-2.2.7:
    <<: *shared_config

    environment:
      CONTAINER_RUBY_VERSION: 2.2.7

  build-ruby-2.3.4:
    <<: *shared_config

    environment:
      CONTAINER_RUBY_VERSION: 2.3.4

  build-ruby-2.4.2:
    <<: *shared_config

    environment:
      CONTAINER_RUBY_VERSION: 2.4.2

workflows:
  version: 2
  build_matrix:
    jobs:
      - build-ruby-2.2.2
      - build-ruby-2.2.7
      - build-ruby-2.3.4
      - build-ruby-2.4.2
